development:
  adapter: postgresql
  encoding: utf8
  database: picks_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: picks_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: picks_production
  pool: 5
